/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type ChatStatus = "active" | "resolved" | "unresolved";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type MessageSender = "admin" | "ai" | "user";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type TyperType = "admin" | "user";

export interface AvailabilitySlots {
  createdAt: Generated<Timestamp | null>;
  dayOfWeek: number;
  enabled: Generated<boolean>;
  endTime: string;
  id: Generated<number>;
  startTime: string;
  timezone: Generated<string>;
  updatedAt: Generated<Timestamp | null>;
}

export interface Chats {
  aiAutoResponseEnabled: boolean | null;
  createdAt: Generated<Timestamp>;
  emailNotificationSent: Generated<boolean>;
  errorContext: string | null;
  feedbackText: string | null;
  id: Generated<number>;
  lastUserMessageAt: Timestamp | null;
  merchantEmail: string;
  ratedAt: Timestamp | null;
  rating: number | null;
  shopDomain: string | null;
  shopName: string | null;
  status: Generated<ChatStatus>;
  updatedAt: Generated<Timestamp>;
  widgetLastSeenAt: Timestamp | null;
  widgetOpen: Generated<boolean | null>;
}

export interface KnowledgeBase {
  answer: string;
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  question: string;
  updatedAt: Generated<Timestamp>;
}

export interface LoginAttempts {
  attemptedAt: Generated<Timestamp>;
  email: string;
  id: Generated<number>;
  success: Generated<boolean>;
}

export interface Messages {
  chatId: number;
  content: string;
  createdAt: Generated<Timestamp>;
  emailNotificationSentForMessage: Generated<boolean>;
  id: Generated<number>;
  imageUrl: string | null;
  sender: MessageSender;
  viewedAt: Timestamp | null;
}

export interface Sessions {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  lastAccessed: Generated<Timestamp>;
  userId: number;
}

export interface Settings {
  adminAgentName: Generated<string | null>;
  aiAgentName: Generated<string | null>;
  autoAiResponseEnabled: Generated<boolean>;
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  updatedAt: Generated<Timestamp>;
}

export interface ShortcutMessages {
  createdAt: Generated<Timestamp | null>;
  id: Generated<number>;
  message: string;
  name: string;
  updatedAt: Generated<Timestamp | null>;
}

export interface TypingStatus {
  chatId: number;
  createdAt: Generated<Timestamp | null>;
  id: Generated<number>;
  lastTypingAt: Generated<Timestamp>;
  typerType: TyperType;
  updatedAt: Generated<Timestamp | null>;
}

export interface UserPasswords {
  passwordHash: string;
  userId: number;
}

export interface Users {
  avatarUrl: string | null;
  createdAt: Generated<Timestamp>;
  displayName: string;
  email: string;
  id: Generated<number>;
  role: Generated<string>;
}

export interface DB {
  availabilitySlots: AvailabilitySlots;
  chats: Chats;
  knowledgeBase: KnowledgeBase;
  loginAttempts: LoginAttempts;
  messages: Messages;
  sessions: Sessions;
  settings: Settings;
  shortcutMessages: ShortcutMessages;
  typingStatus: TypingStatus;
  userPasswords: UserPasswords;
  users: Users;
}


// Use these for zod schema enums or other purposes, since the kysely enums are just types
export const ChatStatusArrayValues: [ChatStatus, ...ChatStatus[]] = ["active","resolved","unresolved"];
export const MessageSenderArrayValues: [MessageSender, ...MessageSender[]] = ["admin","ai","user"];
export const TyperTypeArrayValues: [TyperType, ...TyperType[]] = ["admin","user"];
// Note: kysely maps the table/column/enum names from snake_case to camelCase and PascalCase. When running SQL statements, make sure to use snake_case, but TypeScript code should use camelCase or PascalCase.